name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 11.4.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^7.0.3
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.20.2
  url_launcher: ^6.2.5
  flutter_vector_icons: ^2.0.0

  #Firebase
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_remote_config: ^5.4.4
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  firebase_pagination: ^4.1.0
  firebase_messaging: ^15.2.6

  flutter_local_notifications: ^17.2.2
  flutter_html: ^3.0.0-beta.2
  flutter_custom_tabs: ^2.0.0+1
  syncfusion_flutter_charts: ^29.1.38
  geocoding: ^4.0.0
  webview_flutter: ^4.7.0
  country_picker: ^2.0.25

  # AUDIO
  audioplayers: ^6.0.0
  #  just_audio: ^0.9.37

  #image:
  image_picker: ^1.0.7
  photo_view: ^0.15.0
  file_picker: ^10.1.9
  lottie: ^3.1.0

  # PAYMENTS
  midpay: ^1.1.7
  phonepe_payment_sdk: ^3.0.0
#  flutter_stripe: ^10.0.0
  # razorpay_flutter: ^1.3.6
#  flutterwave_standard: ^1.0.8
  # cinetpay: ^1.0.7
  # flutter_paypal_checkout:
  #   git:
  #     url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
  #     ref: main

#  flutter_paystack:
#    git:
#      url: https://github.com/Raj-GMITS/flutter_paystack.git
#      ref: master

  flutter_localizations:
    sdk: flutter

  uuid: any
  crypto: any
  path: any
  path_provider: any
  async: any
  firebase_app_check: ^0.3.2+7
#dependency_overrides:
#  intl: any
#  flutterwave_standard: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  change_app_package_name: ^1.5.0
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/upi_payment/
    - assets/lottie/

