name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 11.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^7.0.3
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.2.0
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5

  # FIREBASE
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  firebase_remote_config: ^5.4.4
  cloud_firestore: ^5.6.8

  # FIREBASE MESSAGING
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1

  # STATE MANAGEMENT
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # ICON
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.9

  # AUDIO
  record: ^4.4.4
  audioplayers: ^6.0.0
#  just_audio: ^0.9.37

  # IMAGE
  image_picker: ^1.0.7
  photo_view: ^0.15.0
  lottie: ^3.1.0

  # OTHER
  country_picker: ^2.0.25
  flutter_custom_tabs: ^2.0.0+1
  permission_handler: ^12.0.0+1
  flutter_html: ^3.0.0-beta.2
  firebase_pagination: ^4.1.0
  webview_flutter: ^4.7.0
  file_picker: ^10.1.9

  # SOCIAL LOGIN
  google_sign_in: ^6.2.1
#  the_apple_sign_in: ^1.1.1

  # PAYMENT GATEWAYS
#  midpay: ^1.1.7
#  phonepe_payment_sdk: ^2.0.1
#  crypto: 3.0.3
#  qr_flutter: ^4.1.0 #required for in pix_flutter
#  pix_flutter: ^2.2.0
#  razorpay_flutter: ^1.3.6
#  flutterwave_standard: ^1.0.8
#  flutter_stripe: ^10.1.1
#  cinetpay: ^1.0.7
#  flutter_paypal_checkout:
#    git:
#      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
#      ref: main
      
#  flutter_paystack:
#    git:
#      url: https://github.com/Raj-GMITS/flutter_paystack.git
#      ref: master

  # MAP
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.1
  geocoding: ^4.0.0

  flutter_localizations:
    sdk: flutter

  path: any
  path_provider: any
  permission_handler_platform_interface: any
  async: any
  uuid: any
  change_app_package_name: ^1.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/upi_payment/
    - assets/lottie/
